# config/packages/framework.yaml (Version Corrigée et Complétée)

framework:
    secret: '%env(APP_SECRET)%'

    # On dit à Symfony de faire confiance aux informations du proxy Nginx.
    # C'est ce qui devrait résoudre le problème de redirection.
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file